// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbpbCt1mgmkOF1_Po7c4jRbEfnV_Pr34',
    appId: '1:444868467771:web:c9764ef533668b1862d01e',
    messagingSenderId: '444868467771',
    projectId: 'autism-support-campanion',
    authDomain: 'autism-support-campanion.firebaseapp.com',
    storageBucket: 'autism-support-campanion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgdZYnJTPcZ-2mEd_rzegYrhsOyEMBdgQ',
    appId: '1:444868467771:android:b95328cd297c7f0f62d01e',
    messagingSenderId: '444868467771',
    projectId: 'autism-support-campanion',
    storageBucket: 'autism-support-campanion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLgO7d9ZOAl8Fdyc_WMIRUyiR21Qs5Sco',
    appId: '1:444868467771:ios:5431398ed76277c562d01e',
    messagingSenderId: '444868467771',
    projectId: 'autism-support-campanion',
    storageBucket: 'autism-support-campanion.appspot.com',
    iosBundleId: 'com.example.autismSupportCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLgO7d9ZOAl8Fdyc_WMIRUyiR21Qs5Sco',
    appId: '1:444868467771:ios:5431398ed76277c562d01e',
    messagingSenderId: '444868467771',
    projectId: 'autism-support-campanion',
    storageBucket: 'autism-support-campanion.appspot.com',
    iosBundleId: 'com.example.autismSupportCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxbpbCt1mgmkOF1_Po7c4jRbEfnV_Pr34',
    appId: '1:444868467771:web:77d8985e8dbc5a1162d01e',
    messagingSenderId: '444868467771',
    projectId: 'autism-support-campanion',
    authDomain: 'autism-support-campanion.firebaseapp.com',
    storageBucket: 'autism-support-campanion.appspot.com',
  );
}
